---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-serving-cert
spec:
  dnsNames:
  - {{ include "tyk-operator-helm.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "tyk-operator-helm.fullname" . }}-webhook-service.{{ .Release.Namespace }}svc.{{ .Values.clusterDnsDomain }}
  issuerRef:
    kind: Issuer
    name: {{ include "tyk-operator-helm.fullname" . }}-selfsigned-issuer
  secretName: {{ include "tyk-operator-helm.fullname" . }}-webhook-server-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}