---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tyk-operator-helm.fullname" . }}-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tyk-operator-helm.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "tyk-operator-helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
