apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "tyk-operator-helm.labels" . | nindent 4 }}
  name: {{ include "tyk-operator-helm.fullname" . }}-controller-manager-webhook-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "tyk-operator-helm.labels" . | nindent 4 }}
